/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.sylvanianhalloween.controller;

import com.example.sylvanianhalloween.model.Drink;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-10-31T00:07:21.774983+09:00[Asia/Tokyo]")
@Validated
@Api(value = "drink", description = "the drink API")
public interface DrinkApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /drink : Get All Drink Menu
     * コラボメニュー（ドリンク）を全て取得します
     *
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Get All Drink Menu", nickname = "getDrink", notes = "コラボメニュー（ドリンク）を全て取得します", response = Drink.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Drink.class, responseContainer = "List") })
    @GetMapping(
        value = "/drink",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Drink>> getDrink() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"price\" : 715, \"name\" : \"ふわふわキャラメルマロンカフェラテ\", \"storeName\" : \"THE CAMP CAFE & GRILL\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /drink/recommend : Get Recommend Drink Menu
     * コラボメニュー（ドリンク）のおすすめを1件取得します
     *
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Get Recommend Drink Menu", nickname = "getDrinkRecommend", notes = "コラボメニュー（ドリンク）のおすすめを1件取得します", response = Drink.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Drink.class) })
    @GetMapping(
        value = "/drink/recommend",
        produces = { "application/json" }
    )
    default ResponseEntity<Drink> getDrinkRecommend() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"price\" : 715, \"name\" : \"ふわふわキャラメルマロンカフェラテ\", \"storeName\" : \"THE CAMP CAFE & GRILL\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
