/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.sylvanianhalloween.controller;

import com.example.sylvanianhalloween.model.Food;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-10-31T00:07:21.774983+09:00[Asia/Tokyo]")
@Validated
@Api(value = "food", description = "the food API")
public interface FoodApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /food : Get All Food Menu
     * コラボメニュー（フード）を全て取得します
     *
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Get All Food Menu", nickname = "getFood", notes = "コラボメニュー（フード）を全て取得します", response = Food.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Food.class, responseContainer = "List") })
    @GetMapping(
        value = "/food",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Food>> getFood() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"price\" : 1595, \"name\" : \"きのことチーズのあつあつハンバーグ\", \"storeName\" : \"アルカサール\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /food/recommend : Get Recommend Food Menu
     * コラボメニュー（フード）のおすすめを1件取得します
     *
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Get Recommend Food Menu", nickname = "getFoodRecommend", notes = "コラボメニュー（フード）のおすすめを1件取得します", response = Food.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Food.class) })
    @GetMapping(
        value = "/food/recommend",
        produces = { "application/json" }
    )
    default ResponseEntity<Food> getFoodRecommend() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"price\" : 1595, \"name\" : \"きのことチーズのあつあつハンバーグ\", \"storeName\" : \"アルカサール\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
